inputs:
  java:
    required: true
    type: string
  python:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    # Cache local repositories. Note that GitHub Actions cache has a 2G limit.
    - name: Cache Scala, Maven and Zinc
      uses: actions/cache@v1
      with:
        path: build
        key: build-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          build-
    - name: Cache Maven local repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ inputs.java }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ inputs.java }}-maven-
    - name: Install JDK ${{ inputs.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.java }}
    - name: Install Python ${{ inputs.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python }}
        architecture: x64
    - name: Install Python packages (Python ${{ inputs.python }})
      shell: bash
      run: python -m pip install -r ./bin/requirements.txt
    - name: Install Graphviz
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y graphviz
