-- Define Test input views
CREATE OR REPLACE TEMPORARY VIEW t1 AS SELECT * FROM VALUES (1, 1), (1, 2) AS t1(a, b);
CREATE OR REPLACE TEMPORARY VIEW t2 AS SELECT * FROM VALUES (1, 1), (1, 2) AS t2(a, b);

-- Defines views for lineage tests
CREATE OR REPLACE TEMPORARY VIEW t3 AS
  SELECT key AS a, sum(CAST(value AS INT)) AS b FROM testdata
  GROUP BY key HAVING b % 2 = 0;

CREATE OR REPLACE TEMPORARY VIEW t4 AS
  SELECT a, b FROM t1
  UNION ALL
  SELECT a, b FROM t2
  UNION ALL
  SELECT a, b FROM t3;

CREATE OR REPLACE TEMPORARY VIEW t5 AS
  SELECT a AS c FROM t2 WHERE b % 3 = 0 ORDER BY c;

CREATE OR REPLACE TEMPORARY VIEW t6 AS
  SELECT t4.a, t3.b FROM t4 LEFT OUTER JOIN t3 ON t4.a = t3.a;

-- LIMIT
CREATE OR REPLACE TEMPORARY VIEW t7 AS
  SELECT * FROM testdata LIMIT 1;
CREATE OR REPLACE TEMPORARY VIEW t8 AS
  SELECT * FROM (SELECT * FROM range(10) LIMIT 1) WHERE id > 3;

-- Example queries in README.md
CREATE OR REPLACE TEMPORARY VIEW v1 AS
SELECT key, SUM(value) s FROM testdata GROUP BY key HAVING s > 100;

CACHE TABLE v1;

CREATE TEMPORARY VIEW v2 AS
SELECT testdata.*, v1.s FROM testdata
  LEFT OUTER JOIN v1 ON testdata.key = v1.key;
