-- Define Test input views
CREATE OR REPLACE TEMPORARY VIEW t1 AS SELECT * FROM VALUES (1, 1), (1, 2) AS t1(k, v1);
CREATE OR REPLACE TEMPORARY VIEW t2 AS SELECT * FROM VALUES (1, 1), (1, 2) AS t2(k, v2);

CREATE OR REPLACE TEMPORARY VIEW t3 AS
  SELECT t1.* FROM t1 NATURAL JOIN t2;

CREATE OR REPLACE TEMPORARY VIEW t4 AS
  SELECT t1.* FROM t1 NATURAL LEFT JOIN t2 ORDER BY v1, v2;

CREATE OR REPLACE TEMPORARY VIEW t5 AS
  SELECT t1.* FROM t1 NATURAL RIGHT JOIN t2;

CREATE OR REPLACE TEMPORARY VIEW t6 AS
  SELECT t1.* FROM t1 NATURAL RIGHT JOIN t2 WHERE v1 > 0;

CREATE OR REPLACE TEMPORARY VIEW t7 AS
  SELECT t1.* FROM t1 NATURAL FULL OUTER JOIN t2;

CREATE OR REPLACE TEMPORARY VIEW t8 AS
  SELECT t1.* FROM t1 INNER JOIN t2 ON t1.k = t2.k;

CREATE OR REPLACE TEMPORARY VIEW t9 AS
  SELECT t1.* FROM t1 LEFT OUTER JOIN t2 ON t1.k = t2.k;

CREATE OR REPLACE TEMPORARY VIEW t10 AS
  SELECT t1.* FROM t1 RIGHT OUTER JOIN t2 ON t1.k = t2.k;

CREATE OR REPLACE TEMPORARY VIEW t11 AS
  SELECT t1.* FROM t1 FULL OUTER JOIN t2 ON t1.k = t2.k;

CREATE OR REPLACE TEMPORARY VIEW t12 AS
  SELECT t1.* FROM t1 LEFT SEMI JOIN t2 ON t1.k = t2.k;

CREATE OR REPLACE TEMPORARY VIEW t13 AS
  SELECT t1.* FROM t1 ANTI JOIN t2 ON t1.k = t2.k;

CREATE OR REPLACE TEMPORARY VIEW t13 AS
  SELECT t1.* FROM t1 CROSS JOIN t2;
