-- Define Test input views
CREATE OR REPLACE TEMPORARY VIEW t1 AS SELECT * FROM VALUES (1, 1), (1, 2) AS t1(a, b);
CREATE OR REPLACE TEMPORARY VIEW t2 AS SELECT * FROM VALUES (1, 1), (1, 2) AS t2(a, b);

CREATE OR REPLACE TEMPORARY VIEW t3 AS
  SELECT b FROM t1
  UNION
  SELECT a FROM t2;

CREATE OR REPLACE TEMPORARY VIEW t4 AS
  SELECT a FROM t1
  INTERSECT
  SELECT b FROM t2;

CREATE OR REPLACE TEMPORARY VIEW t5 AS
  SELECT a FROM t1
  EXCEPT
  SELECT a FROM t2;

CREATE OR REPLACE TEMPORARY VIEW t6 AS
  SELECT * FROM t3
  UNION ALL
  SELECT * FROM t4
  UNION ALL
  SELECT * FROM t5;
