-- Define Test input views
CREATE OR REPLACE TEMPORARY VIEW t1 AS SELECT * FROM VALUES (1, 1), (1, 2) AS t1(a, b);
CREATE OR REPLACE TEMPORARY VIEW t2 AS SELECT * FROM VALUES (1, 1), (1, 2) AS t2(a, b);

-- Defines views for lineage tests
CREATE OR REPLACE TEMPORARY VIEW t3 AS
  SELECT key AS a, sum(CAST(value AS INT)) AS b FROM testdata
  GROUP BY key HAVING b % 2 = 0;

CREATE OR REPLACE TEMPORARY VIEW t4 AS
  SELECT a, b FROM t1
  UNION ALL
  SELECT a, b FROM t2
  UNION ALL
  SELECT a, b FROM t3;

CREATE OR REPLACE TEMPORARY VIEW t5 AS
  SELECT a AS c FROM t2 WHERE b % 3 = 0 ORDER BY c;

CREATE OR REPLACE TEMPORARY VIEW t6 AS
  SELECT t4.a, t3.b FROM t4 LEFT OUTER JOIN t3 ON t4.a = t3.a;
