-- Aliased subqueries in FROM clause
CREATE OR REPLACE TEMPORARY VIEW t1 AS
  SELECT * FROM (SELECT * FROM testData) AS t WHERE key = 1;

CREATE OR REPLACE TEMPORARY VIEW t2 AS
  FROM (SELECT * FROM testData WHERE key = 1) AS t SELECT *;

-- Optional `AS` keyword
CREATE OR REPLACE TEMPORARY VIEW t3 AS
  SELECT * FROM (SELECT * FROM testData) t WHERE key = 1;

CREATE OR REPLACE TEMPORARY VIEW t4 AS
  FROM (SELECT * FROM testData WHERE key = 1) t SELECT *;

-- Disallow unaliased subqueries in FROM clause
CREATE OR REPLACE TEMPORARY VIEW t5 AS
  SELECT * FROM (SELECT * FROM testData) WHERE key = 1;

CREATE OR REPLACE TEMPORARY VIEW t6 AS
  FROM (SELECT * FROM testData WHERE key = 1) SELECT *;
