name: Reusable workflow for Neo4j tests

on:
  workflow_call:
    inputs:
      java:
        required: true
        type: string
    secrets:
      uri:
        required: true
      user:
        required: true
      passwd:
        required: true

jobs:
  neo4j-tests:
    name: Run Neo4j tests
    runs-on: ubuntu-latest
    env:
      SPARK_LOCAL_IP: localhost
      MAVEN_OPTS: -Xmx1g
    steps:
      - name: Checkout spark-sql-flow-plugin repository
        uses: actions/checkout@v2
        # In order to fetch changed files
        with:
          fetch-depth: 0
      - name: Init test env
        uses: ./.github/actions/setup
        with:
          java: ${{ inputs.java }}
          python: 3.7  # Not used in this test
      - name: Run tests
        env:
          NEO4J_AURADB_URI: ${{ secrets.uri}}
          NEO4J_AURADB_USER: ${{ secrets.user}}
          NEO4J_AURADB_PASSWD: ${{ secrets.passwd}}
        run: |
          ./build/mvn -q clean package -DskipTests
          ./build/mvn -q -Dtest=none -DwildcardSuites=org.apache.spark.sql.flow.sink.Neo4jAuraSinkSuite test
      - name: Upload test results to report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: neo4j-test-results-jdk${{ inputs.java }}
          path: "./target/surefire-reports/*.xml"
      - name: Upload unit tests log files
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: neo4j-tests-log-jdk${{ inputs.java }}
          path: "./target/unit-tests.log"
